services:
  web:
    container_name: tax_form_hub_staging
    build:
      context: .
      dockerfile: Dockerfile
    user: root 
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${WWW_PORT}:${WWW_PORT}"
      - "${WWW_SSL_PORT}:${WWW_SSL_PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html  # Mount source code for live editing
      - bundle_cache:/usr/local/bundle  # Cache gems
      - node_modules:/var/www/html/node_modules  # Cache node modules
    restart: unless-stopped
    stdin_open: true
    tty: true


  db:
    container_name: tax_form_hub_staging_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data_staging:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT2}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped


volumes:
  pg_data_staging:
  bundle_cache:
  node_modules:
